### PR TITLE
[WIP] Implement BIP174 

### PR DESCRIPTION
**Pull request by araspitzu**
This pull request implements the [PartiallySignedTransaction format](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) , it's a new format used to standardize partially signed transactions. I believe it can be useful in bitcoin-lib, for example if eclair-wallet wants to interact with hardware wallets. The implementation aims to be fully compliant with the "official" one from bitcoin-core, [here](https://github.com/bitcoin/bitcoin/pull/12136) . Currently the only the serialization/deserialization code is done, i would like to discuss if it's desiderable to have also the creator/signer/combiner features. While not entirely finished i am opening the pull request in order to allow incremental review.

### CODE REVIEW

**Comment by sstone** [comment]
Thanks! I was also looking at this and monitoring the BIP and core's PR. I've added the WIP tag to the PR

**Comment by achow101** [comment]
Just so you know, the serialization format may be changing drastically soon. Please see the bitcoin-dev mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-June/016121.html and send any comments you have.

**Comment by araspitzu** [comment]
Thanks for the heads up, I've been following the discussion on bitcoin-dev but i actually missed the latest comments.

**Comment by araspitzu** [comment]
BIP174 is changing, I'm closing this for now.

**Pull request closed without merging**
